-- ═══════════════════════════════════════════════════════════════════
-- BASELINE SCHEMA — escapenfly-crm Supabase project (zkhbaisggymbmurqxejk)
-- Reflects production as of 17 Sep 2026. Generated by introspecting
-- pg_catalog/information_schema directly (tables, constraints, indexes,
-- functions, views, RLS policies, grants) — a pg_dump --schema-only
-- equivalent, since this repo never had one before. See README.md for
-- why this exists and what it does/doesn't do.
--
-- This is NOT meant to be applied to the production project (it already
-- has every one of these objects — every CREATE TABLE here would fail
-- with "relation already exists"). Its purpose is so that
-- create_branch()/`supabase branches create` replays a complete schema
-- onto a FRESH preview branch instead of an empty database — see the
-- README note on the one remaining manual step needed for that.
--
-- Verified end-to-end before this file was written: applied this exact
-- SQL (in the same order below) to a disposable throwaway Supabase
-- branch, 0 errors across every statement, then cross-checked object
-- counts against production directly — both sides: 51 tables, 120
-- constraints, 103 indexes, 22 policies, 1 view. That branch was then
-- deleted. Not applied to production itself, per instruction.
-- ═══════════════════════════════════════════════════════════════════

-- ── EXTENSIONS ──
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ── TABLES ──

CREATE TABLE public.activity_log (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  customer_id uuid,
  enquiry_id uuid,
  activity_type text,
  direction text DEFAULT 'outbound'::text,
  summary text,
  detailed_notes text,
  outcome text,
  next_action text,
  next_action_date date,
  logged_by text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.ai_chats (
  phone text NOT NULL,
  msgs jsonb DEFAULT '[]'::jsonb NOT NULL,
  last_msg text,
  last_reply text,
  last_lead_sig text,
  muted boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  campaign_code text,
  broadcast_code text,
  lead_source text,
  pdf_sent_at timestamp with time zone,
  handed_over_at timestamp with time zone
);

CREATE TABLE public.attendance (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  employee_id uuid,
  date date NOT NULL,
  check_in_at timestamp with time zone,
  check_out_at timestamp with time zone,
  mode text DEFAULT 'office'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.audit_log (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  table_name text,
  record_id uuid,
  action text,
  field_changed text,
  old_value text,
  new_value text,
  changed_by text,
  changed_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.bookings (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  booking_number text,
  enquiry_id uuid,
  quotation_id uuid,
  customer_id uuid,
  customer_number text,
  assigned_to_email text,
  assigned_to_name text,
  name text NOT NULL,
  phone text,
  email text,
  destination text,
  departure_date date,
  return_date date,
  nights integer,
  pax_adults integer DEFAULT 2,
  pax_children integer DEFAULT 0,
  hotel_name text,
  hotel_category text,
  airline_pnr text,
  total_amount numeric DEFAULT 0,
  amount_paid numeric DEFAULT 0,
  amount_due numeric DEFAULT 0,
  vendor_cost numeric DEFAULT 0,
  margin numeric DEFAULT 0,
  vineet_firm_amount numeric DEFAULT 0,
  vivek_firm_amount numeric DEFAULT 0,
  status text DEFAULT 'confirmed'::text,
  google_drive_link text,
  notes text,
  cost_rows jsonb DEFAULT '[]'::jsonb,
  payments jsonb DEFAULT '[]'::jsonb,
  documents jsonb DEFAULT '[]'::jsonb,
  reminders jsonb DEFAULT '[]'::jsonb,
  confirmed_snapshot jsonb,
  is_deleted boolean DEFAULT false,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  cost_sets jsonb DEFAULT '[]'::jsonb,
  guesto_link text,
  service_type text,
  travellers jsonb DEFAULT '[]'::jsonb,
  service_details jsonb DEFAULT '{}'::jsonb,
  history jsonb DEFAULT '[]'::jsonb,
  is_commissionable boolean,
  tcs_amount numeric,
  gst_on_markup_amount numeric,
  total_tax_amount numeric
);

CREATE TABLE public.branches (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  branch_code text NOT NULL,
  branch_name text NOT NULL,
  branch_type text DEFAULT 'branch'::text,
  address text,
  city text,
  phone text,
  email text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.campaign_contacts (
  phone text NOT NULL,
  campaign_code text NOT NULL,
  channel text NOT NULL,
  broadcast_code text,
  ad_id text,
  ctwa_clid text,
  bound_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.campaigns (
  campaign_code text NOT NULL,
  product_name text NOT NULL,
  keyword text,
  status text DEFAULT 'draft'::text NOT NULL,
  sells_from date,
  sells_until date,
  pdf_url text,
  opening_line text,
  handover_line text,
  knowledge text,
  keywords text[] DEFAULT '{}'::text[],
  broadcast_codes text[] DEFAULT '{}'::text[],
  platform_campaign_id text,
  platform_ad_ids text[] DEFAULT '{}'::text[],
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.costing_audits (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  cost_set_id text,
  triggered_by text NOT NULL,
  grounding_hash text NOT NULL,
  grounding_snapshot jsonb NOT NULL,
  model text NOT NULL,
  prompt_version text NOT NULL,
  status text NOT NULL,
  flags jsonb,
  raw_response jsonb,
  error text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.costing_lines (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  quotation_id uuid,
  enquiry_id uuid,
  sort_order integer DEFAULT 0,
  category text,
  vendor_id uuid,
  vendor_name text,
  description text,
  item_details text,
  original_currency text DEFAULT 'INR'::text,
  original_amount numeric DEFAULT 0,
  exchange_rate numeric DEFAULT 1,
  net_cost_inr numeric DEFAULT 0,
  markup_amount numeric DEFAULT 0,
  markup_pct numeric DEFAULT 0,
  tax_type text DEFAULT '18gst'::text,
  gst_amount numeric DEFAULT 0,
  tcs_amount numeric DEFAULT 0,
  sell_price_inr numeric DEFAULT 0,
  firm text DEFAULT 'vineet'::text,
  client_reminder text,
  client_reminder_date date,
  vendor_reminder text,
  vendor_reminder_date date,
  notes text,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  margin_type text
);

CREATE TABLE public.customer_notes (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  customer_id uuid,
  enquiry_id uuid,
  note_type text DEFAULT 'internal'::text,
  direction text DEFAULT 'inbound'::text,
  summary text,
  detailed_note text,
  next_action text,
  next_action_date date,
  is_private boolean DEFAULT false,
  created_by text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.customer_profile (
  phone text NOT NULL,
  profile jsonb DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.customers (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  customer_number text,
  name text NOT NULL,
  phone text,
  alternate_phone text,
  email text,
  whatsapp_number text,
  customer_type text DEFAULT 'individual'::text,
  company_name text,
  gst_number text,
  source text,
  tags text[],
  anniversary_date date,
  preferred_hotel_category text,
  notes text,
  lifetime_value numeric DEFAULT 0,
  total_bookings integer DEFAULT 0,
  last_travel_date date,
  branch_id uuid,
  assigned_manager text,
  is_active boolean DEFAULT true,
  is_deleted boolean DEFAULT false,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.dm_sessions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  channel text NOT NULL,
  platform_user_id text NOT NULL,
  page_id text,
  phone text,
  profile_name text,
  last_inbound_at timestamp with time zone,
  handed_off boolean DEFAULT false NOT NULL,
  handed_off_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.dmc_vendor_numbers (
  phone text NOT NULL,
  name text,
  added_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.documents (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  document_type text,
  document_name text,
  google_drive_link text,
  status text DEFAULT 'requested'::text,
  requested_date date,
  received_date date,
  verified_date date,
  expiry_date date,
  notes text,
  uploaded_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.employee_targets (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  employee_email text NOT NULL,
  month text NOT NULL,
  target_profit_amount numeric DEFAULT 0 NOT NULL,
  set_by text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.enquiries (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  enquiry_number text,
  customer_id uuid,
  assigned_to_email text,
  assigned_to_name text,
  branch_id uuid,
  source text,
  referral_name text,
  enquiry_type text DEFAULT 'holiday'::text,
  original_message_text text,
  travel_month text,
  travel_flexibility text DEFAULT 'fixed'::text,
  pax_adults integer DEFAULT 2,
  pax_children integer DEFAULT 0,
  pax_infants integer DEFAULT 0,
  special_occasion text,
  budget_min numeric,
  budget_max numeric,
  notes text,
  internal_notes text,
  status text DEFAULT 'new'::text,
  lost_reason text,
  priority text DEFAULT 'normal'::text,
  followup_date date,
  first_response_at timestamp with time zone,
  last_activity_at timestamp with time zone,
  packages jsonb DEFAULT '[]'::jsonb,
  reminders jsonb DEFAULT '[]'::jsonb,
  history jsonb DEFAULT '[]'::jsonb,
  is_deleted boolean DEFAULT false,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  cost_rows jsonb DEFAULT '[]'::jsonb,
  cost_sets jsonb DEFAULT '[]'::jsonb,
  phone text,
  visa_appointment_date date,
  booking_notified boolean DEFAULT false,
  guesto_link text,
  last_stale_alert_at timestamp with time zone,
  quote_amt numeric,
  re_quote_amt numeric,
  medium text,
  campaign_code text,
  platform_campaign_id text,
  platform_adset_id text,
  platform_ad_id text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  gclid text,
  fbclid text,
  landing_page text,
  referrer text,
  first_touch_source text,
  first_touch_campaign_code text,
  whatsapp_broadcast_code text,
  is_commissionable boolean,
  tcs_amount numeric,
  gst_on_markup_amount numeric,
  total_tax_amount numeric
);

CREATE TABLE public.exchange_rates (
  currency_code text NOT NULL,
  base_rate_inr numeric NOT NULL,
  markup_pct numeric DEFAULT 2.0 NOT NULL,
  source text DEFAULT 'manual'::text NOT NULL,
  last_fetched timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  effective_rate_inr numeric GENERATED ALWAYS AS ((base_rate_inr * ((1)::numeric + (markup_pct / 100.0)))) STORED,
  rate_type text DEFAULT 'tt'::text NOT NULL
);

CREATE TABLE public.founder_notes (
  destination text NOT NULL,
  visa_info text,
  tips text,
  updated_at timestamp with time zone DEFAULT now(),
  min_budget_inr numeric,
  min_budget_note text,
  ideal_duration text,
  visa_complexity text,
  rejection_patterns text,
  best_airlines text,
  best_hotel_areas text,
  common_mistakes text,
  seasonal_advice text,
  consultant_notes text,
  post_trip_feedback text,
  ideal_for text,
  avoid_if text,
  hidden_gem text,
  money_saving_tip text,
  luxury_upgrade text,
  must_not_miss text,
  first_time_traveller_advice text
);

CREATE TABLE public.historical_quotes (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  guesto_quote_id integer,
  share_link text,
  created_date date,
  customer text,
  lead_passenger text,
  pax_adults integer,
  pax_children integer,
  pax_infants integer,
  destinations text[],
  destinations_raw text,
  trip_start_date date,
  trip_end_date date,
  duration_nights integer GENERATED ALWAYS AS ((trip_end_date - trip_start_date)) STORED,
  trip_title text,
  detail_level text DEFAULT 'summary'::text NOT NULL,
  itinerary_detail jsonb,
  source_page integer,
  extraction_notes text,
  extracted_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.internal_notifications (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  notification_type text NOT NULL,
  summary text NOT NULL,
  enquiry_id uuid,
  booking_id uuid,
  assigned_to_email text,
  is_read boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.leave_requests (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  employee_id uuid,
  leave_type text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  reason text,
  status text DEFAULT 'pending'::text,
  requested_at timestamp with time zone DEFAULT now(),
  decided_by text,
  decided_at timestamp with time zone,
  history jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.marketing_assets (
  id text NOT NULL,
  type text NOT NULL,
  platform text,
  campaign_code text,
  title text,
  content text,
  asset_url text,
  status text DEFAULT 'draft'::text NOT NULL,
  scheduled_for timestamp with time zone,
  published_at timestamp with time zone,
  approved_by text,
  approved_at timestamp with time zone,
  rejection_reason text,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  brand text,
  objective text,
  budget numeric,
  notes text,
  source_ref text,
  hook text,
  script text,
  shot_notes text,
  guardrails text,
  fact_sources text,
  files text,
  pillar text,
  production_status text DEFAULT 'briefed'::text
);

CREATE TABLE public.marketing_assets_archive_20260907 (
  id text,
  type text,
  platform text,
  campaign_code text,
  title text,
  content text,
  asset_url text,
  status text,
  scheduled_for timestamp with time zone,
  published_at timestamp with time zone,
  approved_by text,
  approved_at timestamp with time zone,
  rejection_reason text,
  created_by text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  is_deleted boolean,
  brand text,
  objective text,
  budget numeric,
  notes text
);

CREATE TABLE public.marketing_brands (
  code text NOT NULL,
  name text NOT NULL,
  goal text,
  primary_metric text,
  pillars text,
  content_source text,
  ig_handle text,
  fb_page_id text,
  gbp_location text,
  whatsapp_number text,
  website text,
  cta_target text,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.marketing_performance (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  campaign_code text NOT NULL,
  platform text,
  reach numeric,
  engagement numeric,
  spend numeric,
  followers_gained numeric,
  source text DEFAULT 'windsor'::text,
  snapshot_date date DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.marketing_publishes (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  asset_id text NOT NULL,
  channel text NOT NULL,
  scheduled_for timestamp with time zone,
  status text DEFAULT 'planned'::text NOT NULL,
  campaign_code text,
  caption text,
  hashtags text,
  link_url text,
  cta_keyword text,
  segment text,
  contacts integer,
  platform_post_id text,
  post_url text,
  verified_at timestamp with time zone,
  error_text text,
  retry_count integer DEFAULT 0,
  published_at timestamp with time zone,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false
);

CREATE TABLE public.markup_defaults (
  category text NOT NULL,
  percent numeric NOT NULL,
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.master_values (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  category text NOT NULL,
  code text NOT NULL,
  label text NOT NULL,
  color_hex text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true
);

CREATE TABLE public.meta_ad_insights (
  id text NOT NULL,
  snapshot_date date NOT NULL,
  level text NOT NULL,
  account_id text NOT NULL,
  campaign_id text,
  campaign_name text,
  adset_id text,
  adset_name text,
  ad_id text,
  ad_name text,
  effective_status text,
  objective text,
  spend numeric DEFAULT 0,
  impressions bigint DEFAULT 0,
  reach bigint DEFAULT 0,
  clicks bigint DEFAULT 0,
  link_clicks bigint DEFAULT 0,
  ctr numeric,
  cpc numeric,
  cpm numeric,
  frequency numeric,
  messaging_conversations_started bigint DEFAULT 0,
  leads bigint DEFAULT 0,
  actions jsonb,
  campaign_code text,
  synced_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.package_lines (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  package_id uuid NOT NULL,
  rate_card_id uuid NOT NULL,
  day_offset integer,
  sort_order integer DEFAULT 0,
  quantity integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.package_modifiers (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  package_id uuid NOT NULL,
  modifier_name text NOT NULL,
  modifier_type text NOT NULL,
  price_delta_per_person numeric NOT NULL,
  currency text DEFAULT 'USD'::text NOT NULL,
  unit text DEFAULT 'per person'::text,
  confidence text DEFAULT 'estimated'::text NOT NULL,
  vendor_name text,
  notes text,
  last_verified_date date DEFAULT CURRENT_DATE NOT NULL,
  is_active boolean DEFAULT true,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.package_price_tiers (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  package_id uuid NOT NULL,
  hotel_category text NOT NULL,
  season_label text,
  season_start date,
  season_end date,
  pax_bracket_label text NOT NULL,
  pax_min integer NOT NULL,
  pax_max integer,
  price_per_person numeric NOT NULL,
  single_supplement numeric,
  currency text DEFAULT 'USD'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.packages (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  package_name text NOT NULL,
  destinations text[] DEFAULT '{}'::text[] NOT NULL,
  package_type text NOT NULL,
  nights integer,
  pax_min integer DEFAULT 1,
  pax_max integer,
  season text,
  fixed_net_cost numeric,
  fixed_cost_expiry date,
  inclusions text[] DEFAULT '{}'::text[],
  exclusions text[] DEFAULT '{}'::text[],
  overview text,
  useful_info text,
  firm text,
  source text,
  last_verified_date date DEFAULT CURRENT_DATE NOT NULL,
  is_active boolean DEFAULT true,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  fixed_net_cost_child numeric,
  currency text DEFAULT 'INR'::text NOT NULL,
  package_scope text DEFAULT 'land_only'::text NOT NULL,
  vendor_name text,
  vendor_contact text,
  day_wise_itinerary jsonb,
  valid_from date,
  fixed_net_cost_infant numeric
);

CREATE TABLE public.payments (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  payment_number text,
  booking_id uuid,
  visa_id uuid,
  customer_id uuid,
  payment_type text DEFAULT 'advance'::text,
  direction text DEFAULT 'received'::text,
  amount_inr numeric NOT NULL,
  payment_date date NOT NULL,
  payment_mode text,
  utr_reference text,
  bank_name text,
  firm text,
  remarks text,
  created_by text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.portal_credentials (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  vendor_name text NOT NULL,
  credential_label text,
  portal_url text,
  login_username text,
  login_password text,
  agent_code text,
  firm text,
  category text,
  access_level text DEFAULT 'manager_above'::text,
  notes text,
  is_active boolean DEFAULT true,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.quotations (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  quotation_number text,
  enquiry_id uuid,
  customer_id uuid,
  version_number integer DEFAULT 1,
  version_label text DEFAULT 'Standard'::text,
  destination text,
  guesto_link text,
  total_sell_price numeric DEFAULT 0,
  total_vendor_cost numeric DEFAULT 0,
  total_markup numeric DEFAULT 0,
  total_gst numeric DEFAULT 0,
  total_tcs numeric DEFAULT 0,
  vineet_firm_amount numeric DEFAULT 0,
  vivek_firm_amount numeric DEFAULT 0,
  validity_date date,
  status text DEFAULT 'draft'::text,
  sent_at timestamp with time zone,
  accepted_at timestamp with time zone,
  snapshot_json jsonb,
  notes text,
  created_by text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.quote_categories (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  category_code text NOT NULL,
  label text NOT NULL,
  source_mode text NOT NULL,
  api_adapter text,
  rate_cards_service_type text,
  markup_category text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_commissionable boolean DEFAULT false NOT NULL
);

CREATE TABLE public.rate_cards (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  destination text NOT NULL,
  service_name text NOT NULL,
  service_type text NOT NULL,
  source text NOT NULL,
  firm text NOT NULL,
  tax_type text GENERATED ALWAYS AS (
CASE
    WHEN (firm = 'vineet'::text) THEN '18gst'::text
    ELSE '5gst_5tcs'::text
END) STORED,
  markup_category text,
  vendor_name text,
  adult_price numeric DEFAULT 0 NOT NULL,
  child_price numeric,
  unit text,
  last_verified_date date DEFAULT CURRENT_DATE NOT NULL,
  is_active boolean DEFAULT true,
  notes text,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  currency text DEFAULT 'INR'::text NOT NULL,
  infant_price numeric
);

CREATE TABLE public.recommendations (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  phone text,
  destination text,
  situation jsonb,
  recommendation_reason text,
  channel text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.reminders (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  entity_type text,
  entity_id uuid,
  reminder_type text DEFAULT 'custom'::text,
  title text NOT NULL,
  description text,
  due_date date,
  assigned_to_email text,
  priority text DEFAULT 'medium'::text,
  status text DEFAULT 'pending'::text,
  completed_by text,
  completed_at timestamp with time zone,
  created_by text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.roles (
  id text NOT NULL,
  name text NOT NULL,
  permissions jsonb DEFAULT '{}'::jsonb NOT NULL,
  is_system boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.sequence_counters (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  entity_type text NOT NULL,
  year integer NOT NULL,
  last_number integer DEFAULT 0,
  prefix text NOT NULL,
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.staff_roles (
  email text NOT NULL,
  role_id text,
  permission_overrides jsonb DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.tasks (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  task_number text,
  task_type text,
  title text NOT NULL,
  description text,
  entity_type text,
  entity_id uuid,
  assigned_to_email text,
  assigned_to_name text,
  created_by text,
  due_date date,
  due_time time without time zone,
  priority text DEFAULT 'medium'::text,
  status text DEFAULT 'pending'::text,
  completed_at timestamp with time zone,
  completion_notes text,
  is_deleted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.team_members (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  role text NOT NULL,
  specialty text,
  branch_id uuid,
  target_monthly_revenue numeric DEFAULT 0,
  can_view_costing boolean DEFAULT true,
  can_view_credentials boolean DEFAULT false,
  can_delete_records boolean DEFAULT false,
  can_view_all_leads boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.travellers (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  customer_id uuid,
  relationship text DEFAULT 'self'::text,
  first_name text NOT NULL,
  last_name text,
  date_of_birth date,
  nationality text DEFAULT 'Indian'::text,
  gender text,
  passport_number text,
  passport_expiry date,
  passport_issuing_country text,
  meal_preference text,
  special_needs text,
  is_primary boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.vendors (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  vendor_code text,
  name text NOT NULL,
  category text,
  sub_category text,
  scope text DEFAULT 'international'::text,
  contact_person text,
  phone text,
  whatsapp text,
  email text,
  website text,
  regions_covered text[],
  destinations_covered text[],
  payment_terms text,
  currency_preference text DEFAULT 'INR'::text,
  avg_response_hours numeric,
  avg_margin_pct numeric,
  total_transactions integer DEFAULT 0,
  quality_rating numeric,
  notes text,
  status text DEFAULT 'active'::text,
  is_deleted boolean DEFAULT false,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.visa_cases (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  visa_number text,
  customer_id uuid,
  booking_id uuid,
  enquiry_id uuid,
  assigned_to_email text,
  assigned_to_name text,
  name text NOT NULL,
  phone text,
  email text,
  pax_count integer DEFAULT 1,
  country text,
  visa_type text DEFAULT 'Tourist'::text,
  infozeal_file_number text,
  application_date date,
  appointment_date date,
  submission_date date,
  expected_decision_date date,
  decision_date date,
  status text DEFAULT 'lead'::text,
  rejection_reason text,
  portal_notes text,
  payment_received numeric DEFAULT 0,
  gross_profit numeric DEFAULT 0,
  priority text DEFAULT 'normal'::text,
  remarks text,
  has_login boolean DEFAULT false,
  login_data jsonb,
  google_drive_link text,
  cost_rows jsonb DEFAULT '[]'::jsonb,
  reminders jsonb DEFAULT '[]'::jsonb,
  history jsonb DEFAULT '[]'::jsonb,
  is_deleted boolean DEFAULT false,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  cost_sets jsonb DEFAULT '[]'::jsonb,
  payments jsonb DEFAULT '[]'::jsonb
);

CREATE TABLE public.visa_intelligence (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  destination_country text NOT NULL,
  visa_requirement text,
  processing_time text,
  documents_required text[],
  validity text,
  entry_type text,
  estimated_fee text,
  consultant_tips text,
  data_confidence text DEFAULT 'needs_refresh'::text NOT NULL,
  last_updated timestamp with time zone,
  source_notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- ── CONSTRAINTS (primary keys, unique, foreign keys, checks) ──

-- Primary keys
ALTER TABLE public.activity_log ADD CONSTRAINT activity_log_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_chats ADD CONSTRAINT ai_chats_pkey PRIMARY KEY (phone);
ALTER TABLE public.attendance ADD CONSTRAINT attendance_pkey PRIMARY KEY (id);
ALTER TABLE public.audit_log ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);
ALTER TABLE public.branches ADD CONSTRAINT branches_pkey PRIMARY KEY (id);
ALTER TABLE public.campaign_contacts ADD CONSTRAINT campaign_contacts_pkey PRIMARY KEY (phone, campaign_code);
ALTER TABLE public.campaigns ADD CONSTRAINT campaigns_pkey PRIMARY KEY (campaign_code);
ALTER TABLE public.costing_audits ADD CONSTRAINT costing_audits_pkey PRIMARY KEY (id);
ALTER TABLE public.costing_lines ADD CONSTRAINT costing_lines_pkey PRIMARY KEY (id);
ALTER TABLE public.customer_notes ADD CONSTRAINT customer_notes_pkey PRIMARY KEY (id);
ALTER TABLE public.customer_profile ADD CONSTRAINT customer_profile_pkey PRIMARY KEY (phone);
ALTER TABLE public.customers ADD CONSTRAINT customers_pkey PRIMARY KEY (id);
ALTER TABLE public.dm_sessions ADD CONSTRAINT dm_sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.dmc_vendor_numbers ADD CONSTRAINT dmc_vendor_numbers_pkey PRIMARY KEY (phone);
ALTER TABLE public.documents ADD CONSTRAINT documents_pkey PRIMARY KEY (id);
ALTER TABLE public.employee_targets ADD CONSTRAINT employee_targets_pkey PRIMARY KEY (id);
ALTER TABLE public.enquiries ADD CONSTRAINT enquiries_pkey PRIMARY KEY (id);
ALTER TABLE public.exchange_rates ADD CONSTRAINT exchange_rates_pkey PRIMARY KEY (currency_code);
ALTER TABLE public.founder_notes ADD CONSTRAINT founder_notes_pkey PRIMARY KEY (destination);
ALTER TABLE public.historical_quotes ADD CONSTRAINT historical_quotes_pkey PRIMARY KEY (id);
ALTER TABLE public.internal_notifications ADD CONSTRAINT internal_notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.marketing_assets ADD CONSTRAINT marketing_assets_pkey PRIMARY KEY (id);
ALTER TABLE public.marketing_brands ADD CONSTRAINT marketing_brands_pkey PRIMARY KEY (code);
ALTER TABLE public.marketing_performance ADD CONSTRAINT marketing_performance_pkey PRIMARY KEY (id);
ALTER TABLE public.marketing_publishes ADD CONSTRAINT marketing_publishes_pkey PRIMARY KEY (id);
ALTER TABLE public.markup_defaults ADD CONSTRAINT markup_defaults_pkey PRIMARY KEY (category);
ALTER TABLE public.master_values ADD CONSTRAINT master_values_pkey PRIMARY KEY (id);
ALTER TABLE public.meta_ad_insights ADD CONSTRAINT meta_ad_insights_pkey PRIMARY KEY (id);
ALTER TABLE public.package_lines ADD CONSTRAINT package_lines_pkey PRIMARY KEY (id);
ALTER TABLE public.package_modifiers ADD CONSTRAINT package_modifiers_pkey PRIMARY KEY (id);
ALTER TABLE public.package_price_tiers ADD CONSTRAINT package_price_tiers_pkey PRIMARY KEY (id);
ALTER TABLE public.packages ADD CONSTRAINT packages_pkey PRIMARY KEY (id);
ALTER TABLE public.payments ADD CONSTRAINT payments_pkey PRIMARY KEY (id);
ALTER TABLE public.portal_credentials ADD CONSTRAINT portal_credentials_pkey PRIMARY KEY (id);
ALTER TABLE public.quotations ADD CONSTRAINT quotations_pkey PRIMARY KEY (id);
ALTER TABLE public.quote_categories ADD CONSTRAINT quote_categories_pkey PRIMARY KEY (id);
ALTER TABLE public.rate_cards ADD CONSTRAINT rate_cards_pkey PRIMARY KEY (id);
ALTER TABLE public.recommendations ADD CONSTRAINT recommendations_pkey PRIMARY KEY (id);
ALTER TABLE public.reminders ADD CONSTRAINT reminders_pkey PRIMARY KEY (id);
ALTER TABLE public.roles ADD CONSTRAINT roles_pkey PRIMARY KEY (id);
ALTER TABLE public.sequence_counters ADD CONSTRAINT sequence_counters_pkey PRIMARY KEY (id);
ALTER TABLE public.staff_roles ADD CONSTRAINT staff_roles_pkey PRIMARY KEY (email);
ALTER TABLE public.tasks ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);
ALTER TABLE public.team_members ADD CONSTRAINT team_members_pkey PRIMARY KEY (id);
ALTER TABLE public.travellers ADD CONSTRAINT travellers_pkey PRIMARY KEY (id);
ALTER TABLE public.vendors ADD CONSTRAINT vendors_pkey PRIMARY KEY (id);
ALTER TABLE public.visa_cases ADD CONSTRAINT visa_cases_pkey PRIMARY KEY (id);
ALTER TABLE public.visa_intelligence ADD CONSTRAINT visa_intelligence_pkey PRIMARY KEY (id);

-- Unique constraints
ALTER TABLE public.bookings ADD CONSTRAINT bookings_booking_number_key UNIQUE (booking_number);
ALTER TABLE public.branches ADD CONSTRAINT branches_branch_code_key UNIQUE (branch_code);
ALTER TABLE public.customers ADD CONSTRAINT customers_customer_number_key UNIQUE (customer_number);
ALTER TABLE public.dm_sessions ADD CONSTRAINT dm_sessions_channel_platform_user_id_key UNIQUE (channel, platform_user_id);
ALTER TABLE public.employee_targets ADD CONSTRAINT employee_targets_employee_email_month_key UNIQUE (employee_email, month);
ALTER TABLE public.enquiries ADD CONSTRAINT enquiries_enquiry_number_key UNIQUE (enquiry_number);
ALTER TABLE public.master_values ADD CONSTRAINT master_values_category_code_key UNIQUE (category, code);
ALTER TABLE public.payments ADD CONSTRAINT payments_payment_number_key UNIQUE (payment_number);
ALTER TABLE public.quotations ADD CONSTRAINT quotations_quotation_number_key UNIQUE (quotation_number);
ALTER TABLE public.quote_categories ADD CONSTRAINT quote_categories_category_code_key UNIQUE (category_code);
ALTER TABLE public.sequence_counters ADD CONSTRAINT sequence_counters_entity_type_key UNIQUE (entity_type);
ALTER TABLE public.tasks ADD CONSTRAINT tasks_task_number_key UNIQUE (task_number);
ALTER TABLE public.team_members ADD CONSTRAINT team_members_email_key UNIQUE (email);
ALTER TABLE public.vendors ADD CONSTRAINT vendors_vendor_code_key UNIQUE (vendor_code);
ALTER TABLE public.visa_cases ADD CONSTRAINT visa_cases_visa_number_key UNIQUE (visa_number);
ALTER TABLE public.visa_intelligence ADD CONSTRAINT visa_intelligence_destination_country_key UNIQUE (destination_country);

-- Foreign keys
ALTER TABLE public.activity_log ADD CONSTRAINT activity_log_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id);
ALTER TABLE public.activity_log ADD CONSTRAINT activity_log_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES enquiries(id);
ALTER TABLE public.attendance ADD CONSTRAINT attendance_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES team_members(id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES enquiries(id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES quotations(id);
ALTER TABLE public.campaign_contacts ADD CONSTRAINT campaign_contacts_campaign_code_fkey FOREIGN KEY (campaign_code) REFERENCES campaigns(campaign_code) ON UPDATE CASCADE;
ALTER TABLE public.costing_lines ADD CONSTRAINT costing_lines_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES vendors(id);
ALTER TABLE public.costing_lines ADD CONSTRAINT costing_lines_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES quotations(id);
ALTER TABLE public.costing_lines ADD CONSTRAINT costing_lines_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES enquiries(id);
ALTER TABLE public.customer_notes ADD CONSTRAINT customer_notes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
ALTER TABLE public.customers ADD CONSTRAINT customers_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES branches(id);
ALTER TABLE public.enquiries ADD CONSTRAINT enquiries_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id);
ALTER TABLE public.enquiries ADD CONSTRAINT enquiries_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES branches(id);
ALTER TABLE public.internal_notifications ADD CONSTRAINT internal_notifications_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES enquiries(id);
ALTER TABLE public.internal_notifications ADD CONSTRAINT internal_notifications_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES bookings(id);
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES team_members(id);
ALTER TABLE public.marketing_publishes ADD CONSTRAINT marketing_publishes_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES marketing_assets(id) ON DELETE CASCADE;
ALTER TABLE public.package_lines ADD CONSTRAINT package_lines_rate_card_id_fkey FOREIGN KEY (rate_card_id) REFERENCES rate_cards(id) ON DELETE RESTRICT;
ALTER TABLE public.package_lines ADD CONSTRAINT package_lines_package_id_fkey FOREIGN KEY (package_id) REFERENCES packages(id) ON DELETE CASCADE;
ALTER TABLE public.package_modifiers ADD CONSTRAINT package_modifiers_package_id_fkey FOREIGN KEY (package_id) REFERENCES packages(id) ON DELETE CASCADE;
ALTER TABLE public.package_price_tiers ADD CONSTRAINT package_price_tiers_package_id_fkey FOREIGN KEY (package_id) REFERENCES packages(id) ON DELETE CASCADE;
ALTER TABLE public.payments ADD CONSTRAINT payments_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id);
ALTER TABLE public.payments ADD CONSTRAINT payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES bookings(id);
ALTER TABLE public.quotations ADD CONSTRAINT quotations_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES enquiries(id);
ALTER TABLE public.quotations ADD CONSTRAINT quotations_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id);
ALTER TABLE public.staff_roles ADD CONSTRAINT staff_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles(id);
ALTER TABLE public.team_members ADD CONSTRAINT team_members_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES branches(id);
ALTER TABLE public.travellers ADD CONSTRAINT travellers_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
ALTER TABLE public.visa_cases ADD CONSTRAINT visa_cases_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id);
ALTER TABLE public.visa_cases ADD CONSTRAINT visa_cases_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES enquiries(id);
ALTER TABLE public.visa_cases ADD CONSTRAINT visa_cases_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES bookings(id);

-- Check constraints
ALTER TABLE public.campaign_contacts ADD CONSTRAINT campaign_contacts_channel_check CHECK ((channel = ANY (ARRAY['whatsapp_broadcast'::text, 'meta_ad'::text, 'inbound'::text, 'manual'::text])));
ALTER TABLE public.campaigns ADD CONSTRAINT campaigns_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'live'::text, 'closed'::text])));
ALTER TABLE public.costing_audits ADD CONSTRAINT costing_audits_entity_type_check CHECK ((entity_type = ANY (ARRAY['lead'::text, 'booking'::text])));
ALTER TABLE public.costing_audits ADD CONSTRAINT costing_audits_triggered_by_check CHECK ((triggered_by = ANY (ARRAY['done_button'::text, 'export_click'::text, 'idle_debounce'::text])));
ALTER TABLE public.costing_audits ADD CONSTRAINT costing_audits_status_check CHECK ((status = ANY (ARRAY['flags'::text, 'no_concerns'::text, 'insufficient_data'::text, 'failed'::text])));
ALTER TABLE public.costing_lines ADD CONSTRAINT costing_lines_margin_type_check CHECK ((margin_type = ANY (ARRAY['markup'::text, 'commission'::text])));
ALTER TABLE public.dm_sessions ADD CONSTRAINT dm_sessions_channel_check CHECK ((channel = ANY (ARRAY['messenger'::text, 'instagram'::text])));
ALTER TABLE public.exchange_rates ADD CONSTRAINT exchange_rates_rate_type_check CHECK ((rate_type = ANY (ARRAY['tt'::text, 'cash'::text])));
ALTER TABLE public.historical_quotes ADD CONSTRAINT historical_quotes_detail_level_check CHECK ((detail_level = ANY (ARRAY['summary'::text, 'detailed'::text])));
ALTER TABLE public.meta_ad_insights ADD CONSTRAINT meta_ad_insights_level_check CHECK ((level = ANY (ARRAY['campaign'::text, 'adset'::text, 'ad'::text])));
ALTER TABLE public.package_modifiers ADD CONSTRAINT package_modifiers_confidence_check CHECK ((confidence = ANY (ARRAY['vendor_confirmed'::text, 'estimated'::text])));
ALTER TABLE public.package_modifiers ADD CONSTRAINT package_modifiers_modifier_type_check CHECK ((modifier_type = ANY (ARRAY['add'::text, 'remove'::text])));
ALTER TABLE public.packages ADD CONSTRAINT packages_source_check CHECK ((source = ANY (ARRAY['viator_api'::text, 'dmc_vendor'::text, 'dmc_fixed_package'::text])));
ALTER TABLE public.packages ADD CONSTRAINT packages_package_scope_check CHECK ((package_scope = ANY (ARRAY['land_only'::text, 'complete_package'::text])));
ALTER TABLE public.packages ADD CONSTRAINT packages_firm_check CHECK ((firm = ANY (ARRAY['vineet'::text, 'vivek'::text])));
ALTER TABLE public.packages ADD CONSTRAINT packages_package_type_check CHECK ((package_type = ANY (ARRAY['composed'::text, 'fixed_net_cost'::text, 'tiered_net_cost'::text])));
ALTER TABLE public.quote_categories ADD CONSTRAINT quote_categories_source_mode_check CHECK ((source_mode = ANY (ARRAY['database'::text, 'api'::text])));
ALTER TABLE public.rate_cards ADD CONSTRAINT rate_cards_firm_check CHECK ((firm = ANY (ARRAY['vineet'::text, 'vivek'::text])));
ALTER TABLE public.rate_cards ADD CONSTRAINT rate_cards_source_check CHECK ((source = ANY (ARRAY['viator_api'::text, 'dmc_vendor'::text, 'dmc_fixed_package'::text])));
ALTER TABLE public.visa_intelligence ADD CONSTRAINT visa_intelligence_entry_type_check CHECK ((entry_type = ANY (ARRAY['single'::text, 'multiple'::text])));
ALTER TABLE public.visa_intelligence ADD CONSTRAINT visa_intelligence_data_confidence_check CHECK ((data_confidence = ANY (ARRAY['verified'::text, 'needs_refresh'::text, 'stale'::text])));
ALTER TABLE public.visa_intelligence ADD CONSTRAINT visa_intelligence_visa_requirement_check CHECK ((visa_requirement = ANY (ARRAY['visa-free'::text, 'evisa'::text, 'visa-on-arrival'::text, 'embassy-visa-required'::text, 'unclear'::text])));

-- ── INDEXES (excludes ones auto-created by the PK/UNIQUE constraints above) ──

CREATE INDEX ai_chats_campaign_idx ON public.ai_chats USING btree (campaign_code, created_at DESC);
CREATE INDEX idx_attendance_employee_date ON public.attendance USING btree (employee_id, date);
CREATE INDEX idx_bookings_customer ON public.bookings USING btree (customer_id);
CREATE INDEX idx_bookings_departure ON public.bookings USING btree (departure_date);
CREATE INDEX campaign_contacts_campaign_idx ON public.campaign_contacts USING btree (campaign_code, bound_at DESC);
CREATE INDEX campaign_contacts_phone_idx ON public.campaign_contacts USING btree (phone);
CREATE INDEX costing_audits_entity_idx ON public.costing_audits USING btree (entity_type, entity_id, created_at DESC);
CREATE INDEX idx_customers_name ON public.customers USING btree (name);
CREATE INDEX idx_customers_phone ON public.customers USING btree (phone);
CREATE INDEX dm_sessions_handed_off_idx ON public.dm_sessions USING btree (handed_off) WHERE (handed_off = true);
CREATE INDEX dm_sessions_phone_idx ON public.dm_sessions USING btree (phone) WHERE (phone IS NOT NULL);
CREATE INDEX idx_enquiries_assigned ON public.enquiries USING btree (assigned_to_email);
CREATE INDEX idx_enquiries_customer ON public.enquiries USING btree (customer_id);
CREATE INDEX idx_enquiries_phone_created ON public.enquiries USING btree (phone, created_at DESC);
CREATE INDEX idx_enquiries_status ON public.enquiries USING btree (status);
CREATE INDEX idx_historical_quotes_destinations ON public.historical_quotes USING gin (destinations);
CREATE INDEX idx_historical_quotes_detail_level ON public.historical_quotes USING btree (detail_level);
CREATE INDEX idx_leave_requests_employee ON public.leave_requests USING btree (employee_id);
CREATE INDEX mp_asset_idx ON public.marketing_publishes USING btree (asset_id);
CREATE INDEX mp_campaign_idx ON public.marketing_publishes USING btree (campaign_code);
CREATE INDEX mp_sched_idx ON public.marketing_publishes USING btree (scheduled_for);
CREATE INDEX mp_status_idx ON public.marketing_publishes USING btree (status);
CREATE INDEX meta_ad_insights_campaign_idx ON public.meta_ad_insights USING btree (campaign_id, snapshot_date DESC);
CREATE INDEX meta_ad_insights_code_idx ON public.meta_ad_insights USING btree (campaign_code, snapshot_date DESC);
CREATE INDEX meta_ad_insights_date_idx ON public.meta_ad_insights USING btree (snapshot_date DESC);
CREATE INDEX meta_ad_insights_level_date_idx ON public.meta_ad_insights USING btree (level, snapshot_date DESC);
CREATE INDEX idx_package_lines_package ON public.package_lines USING btree (package_id);
CREATE INDEX idx_package_lines_rate_card ON public.package_lines USING btree (rate_card_id);
CREATE INDEX idx_package_modifiers_package ON public.package_modifiers USING btree (package_id);
CREATE INDEX idx_package_price_tiers_package ON public.package_price_tiers USING btree (package_id);
CREATE INDEX idx_packages_destinations ON public.packages USING gin (destinations);
CREATE INDEX idx_rate_cards_destination ON public.rate_cards USING btree (destination);
CREATE INDEX idx_rate_cards_source ON public.rate_cards USING btree (source);
CREATE INDEX idx_rate_cards_stale ON public.rate_cards USING btree (last_verified_date) WHERE (is_active = true);
CREATE INDEX idx_recommendations_destination ON public.recommendations USING btree (destination);
CREATE INDEX idx_recommendations_phone ON public.recommendations USING btree (phone);
CREATE INDEX idx_visa_intelligence_dest ON public.visa_intelligence USING btree (destination_country);

-- ── FUNCTIONS AND VIEWS ──

CREATE OR REPLACE FUNCTION public.campaign_for_contact(p_phone text, p_text text DEFAULT NULL::text)
 RETURNS TABLE(campaign_code text, product_name text, pdf_url text, opening_line text, handover_line text, knowledge text, matched_by text)
 LANGUAGE sql
 STABLE
AS $function$
  select * from (
    (select c.campaign_code, c.product_name, c.pdf_url, c.opening_line,
            c.handover_line, c.knowledge, ('binding:' || cc.channel)::text
     from public.campaign_contacts cc
     join public.campaigns c on c.campaign_code = cc.campaign_code
     where cc.phone = p_phone
       and c.status = 'live'
       and (c.sells_until is null or c.sells_until >= current_date)
     order by cc.bound_at desc
     limit 1)
    union all
    (select c.campaign_code, c.product_name, c.pdf_url, c.opening_line,
            c.handover_line, c.knowledge, 'keyword'::text
     from public.campaigns c
     where c.status = 'live'
       and (c.sells_until is null or c.sells_until >= current_date)
       and p_text is not null
       and exists (select 1 from unnest(c.keywords) k
                   where lower(p_text) like '%' || lower(k) || '%')
       and not exists (
             select 1 from public.campaign_contacts cc2
             join public.campaigns c2 on c2.campaign_code = cc2.campaign_code
             where cc2.phone = p_phone and c2.status = 'live'
               and (c2.sells_until is null or c2.sells_until >= current_date))
     order by c.campaign_code
     limit 1)
  ) r
  limit 1;
$function$;

CREATE OR REPLACE FUNCTION public.next_number(p_entity text)
 RETURNS text
 LANGUAGE plpgsql
AS $function$
declare
  v_row sequence_counters%rowtype;
  v_year int := extract(year from now())::int;
  v_num int;
  v_result text;
begin
  update sequence_counters
  set last_number = last_number + 1, updated_at = now()
  where entity_type = p_entity
  returning * into v_row;

  if not found then
    raise exception 'Unknown entity type: %', p_entity;
  end if;

  v_num := v_row.last_number;

  case p_entity
    when 'customer' then v_result := 'CUS-' || lpad(v_num::text, 6, '0');
    when 'enquiry'  then v_result := 'ENQ-' || v_year || '-' || lpad(v_num::text, 6, '0');
    when 'quotation'then v_result := 'QT-'  || v_year || '-' || lpad(v_num::text, 6, '0');
    when 'booking'  then v_result := 'BK-'  || v_year || '-' || lpad(v_num::text, 6, '0');
    when 'visa'     then v_result := 'VISA-'|| v_year || '-' || lpad(v_num::text, 6, '0');
    when 'payment'  then v_result := 'PMT-' || v_year || '-' || lpad(v_num::text, 6, '0');
    when 'task'     then v_result := 'TSK-' || v_year || '-' || lpad(v_num::text, 6, '0');
    else v_result := upper(p_entity) || '-' || lpad(v_num::text, 6, '0');
  end case;

  return v_result;
end;
$function$;

-- Defined but currently unused: no triggers reference it (checked pg_trigger directly).
CREATE OR REPLACE FUNCTION public.update_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

CREATE OR REPLACE VIEW public.campaign_health AS
 WITH conv AS (
         SELECT COALESCE(c.campaign_code, '(unattributed)'::text) AS campaign_code,
            count(*) AS conversations,
            count(*) FILTER (WHERE (jsonb_array_length(c.msgs) = 2)) AS one_and_done,
            count(*) FILTER (WHERE (c.pdf_sent_at IS NOT NULL)) AS pdf_sent,
            count(*) FILTER (WHERE (c.handed_over_at IS NOT NULL)) AS handed_over,
            count(*) FILTER (WHERE ((((c.msgs -> 1) ->> 'content'::text) ~~* '%holiday%'::text) AND (((c.msgs -> 1) ->> 'content'::text) ~~* '%visa%'::text) AND (((c.msgs -> 1) ->> 'content'::text) ~~* '%flight%'::text))) AS generic_reply
           FROM ai_chats c
          WHERE (c.created_at >= (CURRENT_DATE - '2 days'::interval))
          GROUP BY COALESCE(c.campaign_code, '(unattributed)'::text)
        ), enq AS (
         SELECT COALESCE(enquiries.campaign_code, '(unattributed)'::text) AS campaign_code,
            count(*) AS enquiries,
            count(enquiries.campaign_code) AS attributed
           FROM enquiries
          WHERE (enquiries.created_at >= (CURRENT_DATE - '2 days'::interval))
          GROUP BY COALESCE(enquiries.campaign_code, '(unattributed)'::text)
        )
 SELECT conv.campaign_code,
    conv.conversations,
    conv.generic_reply,
    round(((100.0 * (conv.generic_reply)::numeric) / (NULLIF(conv.conversations, 0))::numeric), 1) AS pct_generic,
    conv.pdf_sent,
    conv.handed_over,
    round(((100.0 * (conv.handed_over)::numeric) / (NULLIF(conv.conversations, 0))::numeric), 1) AS pct_handover,
    round(((100.0 * (conv.one_and_done)::numeric) / (NULLIF(conv.conversations, 0))::numeric), 1) AS pct_one_and_done,
    COALESCE(enq.enquiries, (0)::bigint) AS enquiries,
    COALESCE(enq.attributed, (0)::bigint) AS enquiries_attributed,
        CASE
            WHEN (conv.conversations < 5) THEN 'too early to judge'::text
            WHEN ((conv.generic_reply)::numeric > ((conv.conversations)::numeric * 0.10)) THEN 'ALARM: Maya is answering blind'::text
            WHEN ((conv.handed_over)::numeric < ((conv.conversations)::numeric * 0.10)) THEN 'ALARM: leads are not reaching a human'::text
            WHEN ((COALESCE(enq.attributed, (0)::bigint) = 0) AND (COALESCE(enq.enquiries, (0)::bigint) > 0)) THEN 'ALARM: attribution is not being written'::text
            WHEN (conv.pdf_sent < conv.handed_over) THEN 'ALARM: promised a document that never sent'::text
            ELSE 'ok'::text
        END AS verdict
   FROM (conv
     LEFT JOIN enq USING (campaign_code))
  ORDER BY conv.conversations DESC;

-- ── ROW LEVEL SECURITY ──
-- Only these 4 tables have RLS actually enabled in production (verified via
-- pg_tables.rowsecurity, not just presence of a policy — see below).
ALTER TABLE public.costing_audits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portal_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_roles ENABLE ROW LEVEL SECURITY;

-- Policies. Note: policies exist on several tables below (activity_log,
-- audit_log, bookings, branches, costing_lines, customer_notes, customers,
-- documents, enquiries, master_values, payments, quotations, reminders,
-- sequence_counters, tasks, team_members, travellers, vendors, visa_cases)
-- whose RLS is NOT enabled per the check above — those policies are
-- currently dormant (defined but inert until RLS is turned on for that
-- table), same shape as the portal_credentials anon_all policy CLAUDE.md
-- describes being found and dropped on 18 Aug 2026. Reproduced here exactly
-- as-is (dormant policies included) since this migration's job is to
-- mirror production state as of 17 Sep 2026, not to fix it.
CREATE POLICY anon_all ON public.activity_log AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON public.audit_log AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON public.bookings AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON public.branches AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_select_only ON public.costing_audits AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY anon_all ON public.costing_lines AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON public.customer_notes AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON public.customers AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON public.documents AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON public.enquiries AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON public.master_values AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON public.payments AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON public.quotations AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON public.reminders AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_select_only ON public.roles AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY anon_all ON public.sequence_counters AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_select_only ON public.staff_roles AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY anon_all ON public.tasks AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON public.team_members AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON public.travellers AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON public.vendors AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON public.visa_cases AS PERMISSIVE FOR ALL TO anon USING (true) WITH CHECK (true);
-- portal_credentials: RLS on, dormant anon_all policy was dropped 18 Aug
-- 2026 with no replacement — full deny for anon, matching CLAUDE.md exactly.
-- No CREATE POLICY statement for it here, deliberately.

-- ── GRANTS ──
-- Default shape: full CRUD to anon/authenticated/service_role on every
-- table and view. Written as multi-table GRANT statements rather than one
-- line per table×role (150+ near-identical lines) — functionally identical
-- to what pg_dump would emit individually.
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE
  public.activity_log, public.ai_chats, public.attendance, public.audit_log,
  public.bookings, public.branches, public.campaign_contacts, public.campaign_health,
  public.campaigns, public.costing_lines, public.customer_notes, public.customer_profile,
  public.customers, public.dm_sessions, public.dmc_vendor_numbers, public.documents,
  public.employee_targets, public.enquiries, public.founder_notes, public.historical_quotes,
  public.internal_notifications, public.leave_requests, public.marketing_assets,
  public.marketing_assets_archive_20260907, public.marketing_brands, public.marketing_performance,
  public.marketing_publishes, public.master_values, public.meta_ad_insights, public.package_lines,
  public.package_modifiers, public.package_price_tiers, public.payments, public.portal_credentials,
  public.quotations, public.recommendations, public.reminders, public.roles,
  public.sequence_counters, public.staff_roles, public.tasks, public.team_members,
  public.travellers, public.vendors, public.visa_cases
TO anon, authenticated, service_role;

-- 28 Aug 2026 "revoke_anon_truncate_delete_core_tables" migration — anon
-- keeps INSERT/SELECT/UPDATE but not DELETE/TRUNCATE on these 6.
GRANT INSERT, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE
  public.exchange_rates, public.markup_defaults, public.packages,
  public.quote_categories, public.rate_cards, public.visa_intelligence
TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE
  public.exchange_rates, public.markup_defaults, public.packages,
  public.quote_categories, public.rate_cards, public.visa_intelligence
TO authenticated, service_role;

-- costing_audits: RLS-gated, anon/authenticated read-only, service_role full.
GRANT SELECT ON TABLE public.costing_audits TO anon, authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.costing_audits TO service_role;
